Algoritmo "Crescente"

Var

    X , Y : inteiro

Inicio

     escreval("Digite dois numeros:")
     leia(X)
     leia(Y)
     
     enquanto X <> Y faca

        se X < Y entao
           escreval("Crescente")
          senao
             escreval("Decrecente")
          fimse
          
             escreval("Digite outros dois numeros:")
             leia(X)
             leia(Y)

       fimenquanto

Fimalgoritmo