Algoritmo "Medidas"

Var

     A, B , C, areaA, areaB, areaC : real

Inicio

      escreva("Digite a medida A: ")
      leia(A)
      escreva("Digite a medida B: ")
      leia(B)
      escreva("Digite a medida C: ")
      leia(C)

      areaA <- A * A
      areaB <- A * B / 2
      areaC <- (( A + B) * C / 2)
      
      escreval ("AREA DO QUADRADO = ", areaA:5:4)
      escreval ("AREA DO TRIANGULO = ", areaB:5:4)
      escreval ("AREA DO TRAPEZIO = ", areaC:5:4)

Fimalgoritmo