Algoritmo "media_ponderada"

Var

   N , i : inteiro
    n1, n2, n3 , media : real

Inicio

      escreva("Quantos casos voce vai digitar? ")
      leia(N)
      
      para i de 1 ate N faca
       escreval("Digite tres numeros: ")
      leia(n1)
      leia(n2)
      leia(n3)


      media <- ( n1 * 2 + n2 * 3 + n3 * 5 ) / 10
      
      escreval("Media:", media:3:1)

    fimpara
      

      

      

Fimalgoritmo